#version: 2.1
#
#orbs:
#  maven: circleci/maven@0.0.12
#
#workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results
#
#
version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  deploy:
    docker:
      - image: cdssnc/aws-cli
    steps:
      - run:
          name: "Set AWS region"
          command: aws configure set region ap-northeast-1
      - run:
          name: "Run AWS CodeDeploy"
          command: aws deploy create-deployment --application-name ${DEPLOY_APPLICATION} --deployment-group-name ${DEPLOY_GROUP} --github-location repository="${DEPLOY_REPOSITORY}",commitId="${CIRCLE_SHA1}"
workflows:
  version: 2
  build_deploy:
    jobs:
      - maven/test:
          command: '-X verify'
      - deploy:
          requires:
            - maven/test
          filters:
            branches:
              only: master