spring:
  datasource:
    url: jdbc:mysql://localhost:3306/semipro?autoReconnect=true&useSSL=false
    username: root
    password: password
#    url: jdbc:mysql://semipro.cluster-ciifr12zggfw.ap-northeast-1.rds.amazonaws.com:3306/semipro?autoReconnect=true&useSSL=false
#    username: fujii_daisuke
#    password: orehatsuiteiru
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      maxActive: 4
      maxIdle: 4
      minIdle: 0
      initialSize: 4
  messages:
    basename: i18n/messages
    cacheDuration: -1
    encoding: UTF-8
  mail:
    host: smtp.gmail.com
    port: 587
    username: red.semipro@gmail.com
    password: qozxlzjnydjasnbr
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      maxFileSize: 10Mb
      maxRequestSize: 10Mb

server:
  port: 8080
#  port: 8085 
logging:
  level:
    root: info
    org.springframework.web: debug
    red.semipro: debug
    red.semipro.domain.repository: debug

# application settings
#custom:
#  application:
#    key1: app_a
#    key2: app_b
#    key3: ajToeoe04jtmtU
#  domain:
#    key1: domain_c
#    key2: domain_d
#  common:
#    key1: common_e
#    key2: common_f
#    datePattern: yyyy-MM-dd

mybatis:
#  mapperLocations: classpath:sqlMapper/*.xml
  type-handlers-package: red.semipro.domain.typehandler
  
# application settings
custom:
  application:
    schema:
      http
    domain:
      localhost:8080
  # 秒/分/時/日/月/曜日
    cron:
      eventon: 0 0 3 * * *
    email:
      fromEmail: d.ziifuu@gmail.com
